# -*- coding: utf-8 -*-
"""NLP Assignment

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kechEYqm-pNKyoxG6bPIcPrCBlZXNLcE
"""

import requests

resp = requests.get('https://ca.trustpilot.com/review/discordapp.com')
from bs4 import BeautifulSoup
import csv
soup = BeautifulSoup(resp.text, 'html.parser')

title = soup.title
company_name = title.get_text()

tsection = soup.find('section', {'class' : 'styles_reviewsContainer__3_GQw'})
tdiv1 = tsection.find('div', {'class' : 'paper_paper__1PY90 paper_outline__lwsUX card_card__lQWDv styles_reviewsOverview__mVIJQ'})
tp1 = tdiv1.find('p', {'class' : 'typography_body-l__KUYFJ typography_appearance-default__AAY17'})
total = tp1.get_text()

def getdate(soup):
  '''div1 = soup.find('div', {'class' : 'styles_cardWrapper__LcCPA styles_show__HUXRb styles_reviewCard__9HxJJ'})'''
  section = soup.find('section', {'class' : 'styles_reviewContentwrapper__zH_9M'})
  div2 = section.find('div', {'class' : 'styles_reviewHeader__iU9Px'})
  div3 = div2.find('div', {'class' : 'typography_body-m__xgxZ_ typography_appearance-subtle__8_H2l styles_datesWrapper__RCEKH'})
  time = div3.find('time')['datetime']
  return time

time  = getdate(soup)
print(time)

def getRating(soup):
  div1 = soup.find('div', {'class' : 'styles_cardWrapper__LcCPA styles_show__HUXRb styles_reviewCard__9HxJJ'})
  section = div1.find('section', {'class' : 'styles_reviewContentwrapper__zH_9M'})
  rating = section.find('div', {'class' : 'styles_reviewHeader__iU9Px'})['data-service-review-rating']
  return rating

def getBody(soup):
  div1 = soup.find('div', {'class' : 'styles_cardWrapper__LcCPA styles_show__HUXRb styles_reviewCard__9HxJJ'})
  section = div1.find('section', {'class' : 'styles_reviewContentwrapper__zH_9M'})
  div2 = section.find('div', {'class' : 'styles_reviewContent__0Q2Tg'})
  p1 = div2.find('p', {'class' : 'typography_body-l__KUYFJ typography_appearance-default__AAY17 typography_color-black__5LYEn'})
  body = p1.get_text()
  return body

